openapi: 3.0.3
info:
  title: Comments Service
  description: Comments
  version: 1.0.0
servers:
  - url: http://localhost:8081/api
tags:
  - name: comments
    description: АПИ комментов
    externalDocs:
paths:
  /comments:
    get:
      tags:
        - comments
      summary: Comments list
      description: Список комментариев с фильтрами
      parameters:
        - name: subject_id
          in: query
          description: Id subject
          required: false
          explode: true
          schema:
            type: integer
        - name: subject
          in: query
          description: Тип субъекта
          required: false
          explode: true
          schema:
            type: string
        - name: date_from
          in: query
          description: Стартовая дата
          required: false
          explode: true
          schema:
            type: string
        - name: date_to
          in: query
          description: Конечная дата
          required: false
          explode: true
          schema:
            type: string
        - name: username
          in: query
          description: Имя юзера
          required: false
          explode: true
          schema:
            type: string
      responses:
        200:
          description: Success, comments list
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CommentList'
    post:
      tags:
        - comments
      summary: Add a new comment to the subject
      description: Add a new comment to the cubject
      operationId: addComment
      requestBody:
        description: Add Comment
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Comment'
        required: true
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AddCommentResponse'
        '500':
          description: Server error
  /comments/{id}:
    get:
      tags:
        - comments
      summary: Получить комментарий
      description: Получить комментарий
      parameters:
        - name: id
          in: path
          description: Id клммента
          required: true
          schema:
            type: integer
      responses:
        200:
          description: Get one comment
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OneComment'

components:
  schemas:
    Comment:
      required:
        - Comment
      type: object
      properties:
        Comment:
          type: object
          example: {
            "username": "Swagger",
            "comment": "Comment from swagger",
            "subject": "seller",
            "subject_id": "1"
          }
    AddCommentResponse:
      type: object
      example: {
        "username": "",
        "comment": "Апи коммент без юзверя d",
        "subject": "seller",
        "subject_id": "1",
        "ip": "172.18.0.1",
        "user_agent": "ifone 18 pro max",
        "create_time": 1685388651,
        "status": 1,
        "id": 21
      }
    OneComment:
      type: object
      example: {
        "id": 7,
        "subject_id": 1,
        "subject": "product",
        "status": 2,
        "ip": "172.19.0.1",
        "user_agent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36",
        "create_time": 1683640800,
        "username": "Праздничный",
        "comment": "Купил на 9 мая"
      }
    CommentList:
      type: array
      example: [
        {
          "id": 7,
          "subject_id": 1,
          "subject": "product",
          "status": 2,
          "ip": "172.19.0.1",
          "user_agent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36",
          "create_time": 1683640800,
          "username": "Праздничный",
          "comment": "Купил на 9 мая"
        }
      ]
